version: '3.8'

services:
  web:
    build: .
    restart: always
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    env_file:
      - env_production
    environment:
      - DB_HOST=db
      - DB_PORT=3306
    depends_on:
      - db
    networks:
      - cmdb_network

  db:
    image: mysql:8.0
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: cmdb
      MYSQL_ROOT_PASSWORD: cmdbIndra
    volumes:
      - /opt/cmdb/mysql:/var/lib/mysql
    networks:
      - cmdb_network

  nginx:
    image: nginx:1.21-alpine
    restart: always
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - cmdb_network

volumes:
  # mysql_data: (Removed in favor of bind mount)
  static_volume:
  media_volume:


networks:
  cmdb_network:
    driver: bridge
